---
title: "Broadband Consulting Tech Requirement"
execute:
  echo: true
  output: true
  message: false
  warning: false
---

_Note: These are key takeaways from discussions with the Broadband team about the process and scope of their day-to-day work..._

Our tradable broadband knowledge set is focused on how to pull people together to plan/build broadband infrastructure in strategic ways.

To do this we need:

  - **Collaboration** and **Share-ability** (!)
      - **Web-based map** views that can be shared and accessed by **URL**
        - Currently, this capability is primarily supported by Carto
        - Potential enablement with ArcGIS Online:
          - “_it seemed like a better version of Carto_” - Myles
        - Felt is also nice https://felt.com/ and work with QGIS
  - Understanding of telecommunications **infrastructure** and landscape:
      - **Where** is/is not
         - Operating footprint
         - Grant funded areas (past awards?)
      - **What** (tech + service level)
        - ISP presence
        - Advertised speeds
          - Categorized by grant criteria (e.g. BEAD)
      - **Who** (ownership)
        - DBA mapped back to single entity (source-of-truth)
        - Funding history (previous grant recipient?)
      - **Density** of (potential) subscribers
      - **Social/Demographic** analysis of (potential) subscribers
          - Calculate route miles needed for potential deployments in more sophisticated manner  
      - at which **scale/granularity** (resoltion): what is the best resolution to provide valuable insight without glutting everythings?
     
  - Understanding **actual performance** (average speeds) of broadband networks
  - Understanding **physical topology** (layout) of existing network
      - Ability to **model** and **compare** models of potential (future) **physical topology** of networks
          - Determine/calculate feasibility by:
            - Costs
            - Route Miles
            - Technology
  - Dynamically assess multiple geographic contexts for potential infrastructure planning
      - compare these contexts
      - non-standard geographies driven by real world requirements
      - Lowest level of geographic context may be neighborhood
      - May approximate mapping of block-level data to non-standard geography; when possible (_this is hard_)
      - Some geography selection is by **name**
        - Ability to map names to geospatial representations
      - Would block-selector tool be helpful?
        - +support for automatically suggesting block set mappings for non-standard geographic features as well as mapping to geographically-relevant names (within limited/scoped contexts)

<hr />

_Note: What follows are additional key takeaways from an MDA discussion about the ways we can/cannot provide access to data..._

We approve access to the following datasets, in the following ways:

- `sch_broadband`
  - BEAD/BCAT (We stand-by the outputs/reports/etc.)
  - Broadband Risk (We stand-by the outputs/reports/etc.)
  - MDA produced data products (codebooks, maps, reports, sheets, etc.)
  - pgAdmin (YES, BUT we cannot QC or guarantee the _resulting_ work product)
  - QGIS (YES, BUT we cannot QC or guarantee the _resulting_ work product)
  - R (YES, BUT we cannot QC or guarantee the _resulting_ work product)

- `acs`
    - ~~pgAdmin~~ (should we support wrangling a tidy dataset in SQL? NO)
    - ~~QGIS~~ (should we support wrangling a tidy dataset in SQL? NO)
    - R (YES, BUT we cannot QC or guarantee the _resulting_ work product)



<hr />

> NOTE: **Fixed Broadband Availability Data comes from the [FCC's National Broadband Map](https://broadbandmap.fcc.gov/data-download/nationwide-data)** <br />
> See the [FCC exploratory data analysis notebook](https://ruralinnovation.github.io/proj-fcc-report/) that Olivier's maintains and updates as each additional data set is ingested: https://ruralinnovation.github.io/proj-fcc-report/ <br />
> To perform place-based analysis on broadband access, service availability, and relative affordability, including broadband serviceable location data, we utilize the [BDC Public Data Downloads](https://broadbandmap.fcc.gov/data-download/nationwide-data) repository and [BDC Public Data API](https://us-fcc.box.com/v/bdc-public-data-api-spec) served by the FCC National Broadband Map. To date, we are not seeking, nor have we been granted access to the Broadband Serviceable Location Fabric dataset (sometimes referred to as the _FCC Broadband Fabric_, _FCC Fabric_, or _Location Fabric_) produced by CQA ([CostQuest Associates](https://www.costquest.com/)).

