---
title: "Broadband data"
execute:
  echo: true
  output: true
  message: false
  warning: false
---


### The available data

The following explanation of the data sourced from the FCC is extracted from CORI's [FCC report](https://ruralinnovation.github.io/proj-fcc-report/){.external target="_blank"}, a work-in-progress exploratory data analysis produced by [Olivier Leroy](https://github.com/defuneste){.external target="_blank"}. Please visit the report for a deeper analysis of various aspects of this data.

We rely on two key datasets from the Federal Communications Commission (FCC):

1) **National Broadband Map** ([NBM](https://broadbandmap.fcc.gov/home){.external target="_blank"}):
- Provides granular information on broadband service availability at specific locations, including details about service providers, technology types, and advertised speeds.

2) **Broadband Funding Map** ([BFM](https://fundingmap.fcc.gov/home){.external target="_blank"}):
- Offers insights into federally funded broadband infrastructure projects, detailing program boundaries and project-level information.

Both datasets are publicly available under permissive licensing, making them invaluable tools for analyzing broadband coverage and funding opportunities. Licensing information can be found [here](https://broadbandmap.fcc.gov/about){.external target="_blank"} and [here](https://fundingmap.fcc.gov/about){.external target="_blank"}, respectively.[^license_and_attribution]

[^license_and_attribution]: <em>License and Attribution language from the FCC<em>:
<br />
<br /> Broadband availability data from the BDC, and data from the U.S. Census Bureau that are presented on this site, are offered free and not subject to copyright restriction. Data and content created by government employees within the scope of their employment are not subject to domestic copyright protection under 17 U.S.C. § 105. See, e.g., [U.S. Government Works](https://www.usa.gov/government-copyright).
<br />
<br /> While not required, when using in your own work content, data, documentation, code, and related materials from fcc.gov or broadbandmap.fcc.gov, we ask that you provide proper attribution of the data. Examples include:
<br />
<br />     Source data: FCC Broadband Funding Map
<br />     Map layer based on FCC BFM
<br />
<br /> CostQuest Associates, Inc. and its third-party licensors, as applicable, own all right, title, and interest, including all intellectual property rights, in and to the data for locations reflected in the Fabric (including the Location ID, latitude and longitude, address, unit count, and building type code for each location in the Fabric). CostQuest is granted certain rights to Fabric correction submissions for the purpose of correcting or otherwise modifying BDC Fabric data. Broadband service providers, governmental entities, and other third parties are able to license Fabric data, including any changes to Fabric data that have been made as a result of challenges, at no cost for purposes of their participation in the FCC's Broadband Data Collection.


#### Data updates

We are documenting the workflow for ingesting and deploy updates from subsequent FCC data releases here: [FCC data updates flow](https://docs.google.com/document/d/1nERUkRjk6ngwBsVpWeMTkuctJUhI1ZiROoL6xUtCQE0/edit?tab=t.0#heading=h.49g6wb3j4cy){.external target="_blank"}

### Broadband Consulting Tech Requirement

_Note: These are key takeaways from discussions with the Broadband team about the process and scope of their day-to-day work..._

Our tradable broadband knowledge set is focused on how to pull people together to plan/build broadband infrastructure in strategic ways.

To do this we need:

  - **Collaboration** and **Share-ability** (!)
      - **Web-based map** views that can be shared and accessed by **URL**
        - Currently, this capability is primarily supported by Carto
        - Potential enablement with ArcGIS Online:
          - “_it seemed like a better version of Carto_” - Myles
        - Felt is also nice https://felt.com/ and work with QGIS
  - Understanding of telecommunications **infrastructure** and landscape:
      - **Where** is/is not
         - Operating footprint
         - Grant funded areas (past awards?)
      - **What** (tech + service level)
        - ISP presence
        - Advertised speeds
          - Categorized by grant criteria (e.g. BEAD)
      - **Who** (ownership)
        - DBA mapped back to single entity (source-of-truth)
        - Funding history (previous grant recipient?)
      - **Density** of (potential) subscribers
      - **Social/Demographic** analysis of (potential) subscribers
          - Calculate route miles needed for potential deployments in more sophisticated manner  
      - at which **scale/granularity** (resoltion): what is the best resolution to provide valuable insight without glutting everythings?
     
  - Understanding **actual performance** (average speeds) of broadband networks
  - Understanding **physical topology** (layout) of existing network
      - Ability to **model** and **compare** models of potential (future) **physical topology** of networks
          - Determine/calculate feasibility by:
            - Costs
            - Route Miles
            - Technology
  - Dynamically assess multiple geographic contexts for potential infrastructure planning
      - compare these contexts
      - non-standard geographies driven by real world requirements
      - Lowest level of geographic context may be neighborhood
      - May approximate mapping of block-level data to non-standard geography; when possible (_this is hard_)
      - Some geography selection is by **name**
        - Ability to map names to geospatial representations
      - Would block-selector tool be helpful?
        - +support for automatically suggesting block set mappings for non-standard geographic features as well as mapping to geographically-relevant names (within limited/scoped contexts)

<hr />

_Note: What follows are additional key takeaways from an MDA discussion about the ways we can/cannot provide access to data..._

We approve access to the following datasets, in the following ways:

- `sch_broadband`
  - BEAD/BCAT (We stand-by the outputs/reports/etc.)
  - Broadband Risk (We stand-by the outputs/reports/etc.)
  - MDA produced data products (codebooks, maps, reports, sheets, etc.)
  - pgAdmin (YES, BUT we cannot QC or guarantee the _resulting_ work product)
  - QGIS (YES, BUT we cannot QC or guarantee the _resulting_ work product)
  - R (YES, BUT we cannot QC or guarantee the _resulting_ work product)

- `acs`
    - ~~pgAdmin~~ (should we support wrangling a tidy dataset in SQL? NO)
    - ~~QGIS~~ (should we support wrangling a tidy dataset in SQL? NO)
    - R (YES, BUT we cannot QC or guarantee the _resulting_ work product)



<hr />

> NOTE: **Fixed Broadband Availability Data comes from the [FCC's National Broadband Map](https://broadbandmap.fcc.gov/data-download/nationwide-data)** <br />
> See the [FCC exploratory data analysis notebook](https://ruralinnovation.github.io/proj-fcc-report/) that Olivier's maintains and updates as each additional data set is ingested: https://ruralinnovation.github.io/proj-fcc-report/ <br />
> To perform place-based analysis on broadband access, service availability, and relative affordability, including broadband serviceable location data, we utilize the [BDC Public Data Downloads](https://broadbandmap.fcc.gov/data-download/nationwide-data) repository and [BDC Public Data API](https://us-fcc.box.com/v/bdc-public-data-api-spec) served by the FCC National Broadband Map. To date, we are not seeking, nor have we been granted access to the Broadband Serviceable Location Fabric dataset (sometimes referred to as the _FCC Broadband Fabric_, _FCC Fabric_, or _Location Fabric_) produced by CQA ([CostQuest Associates](https://www.costquest.com/)).

