---
title: "Grant"
execute:
  echo: true
  output: true
  message: false
  warning: false
format:
  html:
    code-fold: true
reference-location: margin
citation-location: margin
---

# AWS Imagine

3 categories:

    - Momentum to Modernize, 

    - Go Further, Faster, 

    - Pathfinder – Generative AI 

## Rules:

- We can submit only submit one application (one categories)

- Round one: open to everyone, round two on invitation

- Proposal w/o any personal info

- US nonprofit with active 501 

### Importants dates

- portal will open on May 3, 2024

- Dead line for round one: **June 3 2024**

- Notification for round 2 July 17 2024


## Good to know / Resources

- [Tutorial Video](https://www.youtube.com/watch?v=AfApI2auGXw)

- My takes on it (1.5 speed video):
    * Importance of holistics approach ie: provide tech + support 

    * "Momentum to modernize": We are really looking for organization that view these types of project as fundational steps" (setting up the fundation to unlock futur doors)

    * "To go further faster award": "Thing big", "highly innovative program", "DevOps"

    * "Always lead the mission with technology as a core strategic enablement"

    * "Senior leader who is the project champion"

    * "convey urgency and importance of your project"

    * "work backward from the end user"

    * "end goal connect your mission"

    * "dynamic dashboard"

    * "what services will it use"

    * "how do the technical elements fits together" 

    * "what skill resources do you have in house"

    * "what yoiu plan to acquire the most"

    * Maybe we can use some AI ML on checking FCC data aginst location (presence or not) and MLAB on quality of services

    * "articulate why each piece of the imagine grant is useful not only cash"  

    * research long term (maybe more for phase 2)

    * automate the ingestion delivery

    * technical diagram: AWS architecture diagrams 


- We can contact the AWS Nonprofits team ([form](https://aws.amazon.com/government-education/contact/)), and should, we need to prepare an **high level summary before**  


## Retro-Planning for the MDA

- Decide on an what we want to do: Dead line May 16

- Write high level summary and get feedback from AWS Team May 17[^aws_ref] 

[^aws_ref]: p11 of AWS Imagine 2024

- Write the grant with feedback from AWS 

- MDA proposition should be done May 24

- Giving us buffer we (Robin?/Mike?) want to submit May 30

## first brainstorm: 

At CORI we are helping rural communities and their leaders understand the rural divide and reduce it.
This is a critical moment for broadband funding and infrastructure expansion that will have major impacts on communities across the nation.
Our broadband team contributes to it and our research team provides insights on how this affects communities.

Both rely on fresh, actionable and easy to share data.
To do that our mapping and data team have been ingested, processed FCC data and shared those results either with web apps or with in-house analytics.
Sadly our manual processes do not allow us:
- to keep up with the volume and frequencies of FCC releases
- to add different source of data and combine them
- get the granularity that expert on the ground needs
- keep memory over time, trends, to drive thought leadership
- expand our audience

In its ever evolving landscape, being able to efficiently capture and store data with the help of AWS infrastructure will create valuable resources for our partner and communities.
Both the "Momentum to Modernize" and "Go Further, Faster" grants could potentially help us and provide new opportunities to become a hub and source of truth/expertise on broadband data.



# Outline of the grant application

(just a copy of AWS pdf / checked if that match also the application portal)

## Organizational Information

1. Full, Registered Organization Name

2. Tax ID

3. Website URL

4. Organization Full Address 

- Street,

- City,

- State, 

- Zip Code

5. Annual Organizational Revenue (most recent fiscal year's, in USD) [Select one]
  a) Less than $50,000
  b) $50,000 - $999,999
  c) $1,000,000 - $4,999,999
  d) $5,000,000 - $9,999,999
  e) $10,000,000 - $99,999,999
  f) $100,000,000 or more
  g) Don’t know/ Not sure

6. Annual IT Budget (most recent fiscal year's expenses in USD)
  a) Less than $10,000
  b) $10,000 - $50,000
  c) $50,000 - $150,000
  d) $150,000 - $500,000
  e) $500,000 or more

7. Proposal Contact 

- First and Last Name, 

- Email Address, 

- Phone Number

~~8. Project Lead (First and Last Name, Email Address, Phone Number)~~ Not in the portal

9. Role in Organization
  a) President or CEO
  b) Other C-Level of executive management
  c) Vice president or equivalent
  d) Board of Directors
  e) Director or equivalent
  f) Manager or equivalent
  g) Generalist, staff, associate, or equivalent
  h) Other

10. Functional Area in Organization
  a) Leadership or overall management
  b) Program management
  c) Event management
  d) Fundraising/ Development
  e) Community outreach
  f) Technology
  g) Human resources
  h) Marketing
  i) Finance
  j) Administration
  k) Other

11. Primary Mission Area
a) Arts, Culture, and Humanities
b) Credit Union
c) Education
d) Environment and Animals
e) Health
f) Human Services
g) International, Foreign Affairs
h) Public, Societal Benefit
i) Religion Related
j) Science, Technology & Social Science
k) Youth Development
l) Mutual/Membership Benefit
m) Public Utilities
n) Unknown, Unclassified

12. Does your organization have an AWS account? [Yes/No]

a) If selected “Yes,” please provide your account ID (if your organization has multiple IDs,
you can provide any one of them)

13. Have you applied for the IMAGINE Grant before? [Yes/No]

-> it will need to confirmed 

## Project Information

1. Which AWS IMAGINE Grant category are you applying for? [select one]
  a) Momentum to Modernize award <-- **The one I think we should apply**
  b) Go Further, Faster award
  c) Pathfinder – Generative AI award

2. What is your project and how does it relate to your organization’s mission? [200 - 350 words]


~~3. (For Pathfinder applicants only) How does generative AI fit into your overall project design? How
will it strategically enhance your mission achievement? [100 - 250 words]~~

~~4. (For Pathfinder applicants only) How is your organization using data to make decisions today?
[100 - 250 words]~~

5. What are the intended outcomes of your project? What new capabilities would it unlock for
your organization? [200 - 350 words]


6. What is driving the need for this specific project? Why now? [200 - 350 words]



7. At what stage is your project currently? [Select one]
  a) Concept
  b) Planning
  c) Under development
  d) Currently running

8. What most closely aligns with what this project will enable your organization to do? [Select one]
  a) Migrate legacy IT systems, applications, and data centers to the cloud.
  b) **Increase productivity with modernized tools, applications, and databases.** <- this one
  c) Increase cost efficiency with optimized IT infrastructure.
  d) Enable business continuity with archive, backup, and disaster recovery.
  e) **Increase resilience, scaling, and availability of existing workloads and databases.** <- this one
  f) Increase security and governance of data/ ensure security compliance. (e.g. HIPAA, SOC)
  g) **Inform better decision making by aggregating disparate data sources and applying
  analytics (e.g., visualization, AI/ML).** <- this one
  h) Enable accurate forecasting based on past data with predictive analysis using machine learning.
  i) Better understand and engage members/donors/beneficiaries by creating a 360 view
  with constituent data.
  j) **Enhance digital content delivery for donors, members, beneficiaries, or other stakeholders (e.g., website, video, mobile app)** <- maybe
  k) Enable multichannel services for constituents and automate simple, clerical tasks for employees (e.g. chatbots, contact centers, GenAI-powered)
  l) Personalize and streamline communications for more effective
  donor/member/constituent engagement and fundraising.
  m) I don’t know how AWS fits into my project at this time, but I am interested in learning
  more.
  n) Other

## Technical Design

1. Describe your project’s technical design at a high level. What does it do and how? [200 - 350
words]

2. What type(s) of workload(s) will your project include? [Select all that apply] (Hint: Learn more
about types of workloads in our latest publication on how nonprofits leverage the cloud today)
  a) Digital content management (e.g. hosting and scaling websites)
  b) Digital content delivery (e.g. virtual events, virtual learning platform)
  c) Net-new application development (e.g. web app, mobile app, SaaS platform)
  d) Application integration (e.g. serverless, microservices, distributed systems)
  e) DevOps pipeline (e.g. CI/CD)
  f) Container orchestration and management
  g) Managed security services
  h) Content storage and backup (e.g. disaster recovery)
  i) Migration and optimization (e.g. systems, data, application)
  j) Virtual desktop
  k) Data lake
  l) Data warehouse
  m) Data analytics and visualization
  n) Managed AI/ML services (e.g. intelligent document processing, image recognition)
  o) AI/ML for research
  p) AI/ML for predictive modeling
  q) Generative AI
  r) Customer experience (e.g. call/contact center, virtual assistant)
  s) Internet of things (IoT)
  t) Blockchain
  u) Other. Please specify:
  v) None of the above

3. Describe the resources and technical skills you may need to complete the project successfully.
Do you have these resources in-house? If no, what will be your plan to acquire the skills
needed? [200 - 350 words]

4. To successfully complete your project, would you need support from a technology and/or
implementation partner? (Hint: An AWS Partner is an external expert who leverages AWS to
build solutions and services for customers. See a list of AWS Partners)
a) Yes, and I already work with a partner/ plan to work with a specific partner.
i. [If selected] Please list partner:
b) Yes, I do not have a partner identified but would like a recommendation.
c) No, I do not plan to work with a partner/ we plan to do the work in-house
d) Other. Please explain:

5. Is your organization’s IT infrastructure currently: [Select one]
  a) On-premises
  b) On AWS
  c) With another provider
  d) Hybrid

6. Is the IT infrastructure for the project you are proposing for this grant opportunity currently:
[Select one]
  a) On-premises
  b) On AWS
  c) Net-new to your organization
  d) With another provider
  e) Hybrid

7. If you were to not receive funding or be awarded the full amount of funding for either award,
would your organization still be able to implement this project?
  a) Yes
  b) No
