---
title: "MDA Team Wiki"
---

We are building a one-of-a-kind, data-driven platform that can provide the whole-systems, integrated model that is necessary to describe and explain the place that **Rural** inhabits within the broader social and economic fabric of the United States. The ultimate goal of those efforts is to energize and guide local ingenuity and leadership within rural communities as they confront the overwhelming organizational challenges involved in the development of an emerging _local_ tech economy. This synthesis has the potential to substantially shift the cultural, intellectual and material/capital contributions of rural people living in rural places.

As the Mapping and Data Analytics team, we are responsible for the foundational data and methodology that underlies any explanatory model that is produced or data product that is delivered and/or published by the [Center on Rural Innovation](https://ruralinnovation.us/) and [Rural Innovation Strategies, Inc.](https://ruralinnovationstrategies.com/), respectively. Inherit in engaging with this responsibility is an ongoing need to map the knowledge that is generated and/or captured by our work to the basic terms of which that knowledge is composed. The collective  and individual professional experience of the MDA team provides a wide breadth of analytical insights into the data that we use, but much of this value is implicit in the final output of our work product, rather than intentionally and continuously integrated into the system on which our work is occurring. As much as possible, we should aim to build a system or a _platform_ for our work that maximizes our ability to sustain and improve our models, as well as the organization's ability to intelligently utilize our models in pursuit of our mission.

::: {.callout-tip}
_Note: See [CORI/RISI Ontology](CORI-Ontology.qmd) to follow/contribute to our refinement of the relevant terms of our analysis._
:::
